using BookSample.Data.Database;
using BookSample.GraphQL.GraphQL;
using BookSample.ReviewAPIClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Kiota.Abstractions.Authentication;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Http.HttpClientLibrary;
using BookSample.GraphQL.GraphQL.Queries;

var builder = WebApplication.CreateBuilder(args);

// Register the EFCore database context
builder.Services.AddDbContext<BookDbContext>(options =>
{
    options.UseNpgsql(builder.Configuration.GetRequired("PostgresConnectionString"));
});

// Register the ReviewClient (generated by Kiota)
builder.Services.AddTransient<IRequestAdapter>(_ => new HttpClientRequestAdapter(new AnonymousAuthenticationProvider()));
builder.Services.AddTransient<ReviewClient>();

// Register and configure HotChocolate
builder.Services
    .AddGraphQLServer()
    .InitializeOnStartup()
    .AddQueryType<Query>()
    .AddTypeExtension<BookQueries>()
    .AddMutationType<Mutation>()
    .AddSubscriptionType<Subscription>()
    .AddInMemorySubscriptions()
    //.AddType<AuthorType>()
    //.AddType<BookType>()
    //.AddType<GenreType>()
    //.AddType<PublisherType>();
    .AddGraphQLTypes()   // Replaces the commented AddType calls above. Uses source-generators to create the types (Available in the HotChocolate.Types.Analyzers NuGet package).
    .SetPagingOptions(new()
    {
        IncludeTotalCount = true,
        DefaultPageSize = 100,
        MaxPageSize = 10000
    })
    .AddMutationConventions()
    .RegisterDbContext<BookDbContext>()
    .AddProjections()
    .AddSorting()
    .AddFiltering();

var app = builder.Build();

//app.UseWebSockets();  // With: Subscriptions via WebSockets      Without: Subscriptions via SSE

// Map the GraphQL endpoint
app.MapGraphQL();

app.Run();
